# Generated by Django 5.2.1 on 2025-05-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text="Image représentant l'article (optionnel)", null=True, upload_to='uploads/articles/', verbose_name="Image de l'article"),
        ),
    ]
